### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by StevenGann** [deatos/HyperVectorDB#2]
I am using HyperVectorDB in an unpublished project. I intend on publishing the project soon, on GitHub and also as a NuGet package.

It would make dependency management easier for my purposes if HyperVectorDB were published on NuGet.

My [PR](https://github.com/deatos/HyperVectorDB/pull/1) is still pending review so I am wondering if this repo is abandoned. If you have no objections, I will publish [my fork of HyperVectorDB](https://github.com/StevenGann/HyperVectorDB/tree/master) to NuGet sometime after July 13th, approximately one month after my PR was opened, and use it as a dependency for my projects until you are able to address this.

Thanks for the awesome project! It has proven extraordinarily useful!

**Comment by deatos** [comment]
Heya repos is not abandoned.  I missed your pull.  Sorry about that.  I will check this out in the next few hours.

**Comment by deatos** [comment]
Thank you for contributing to HyperVectorDB! I apologize for the delay. I’ve reviewed and merged your pull request. It’s great to hear that the project has been useful to you.

I’m not very familiar with the process of publishing on NuGet, but I will start looking into it over the next few days. Knowing that others are actively using the project is very encouraging, and I will make efforts to continue development and make the project more contributor-friendly.

If you are interested in collaborating further, please let me know.

Feel free to reach out to me on Telegram: https://t.me/deatos

Thank you once again for your contribution and support!

**Comment by StevenGann** [comment]
Absolutely, I'd like to collaborate further.
I was looking to build my own vector database for a project, started getting lost in some of the implementation details, and stumbled on your repo. It was most of the way to what I needed so I thought it made more sense to work with what you already accomplished.

I'll have another PR soon. I am working on adding unit tests and API documentation. I think there's more optimization that could be done, but the features I added cover all my current needs. If you have ideas for further improvements I'd love to help out.

I have two projects I'm working on that need a locally-hosted RAG with embeddings and LLMs running on a stack of A100 GPUs. To make it useful across multiple projects, I'm making a C# library for RAGs. Once HyperVectorDB is on NuGet, I'll publish my RagSharp library on GitHub and eventaully NuGet too. I'd welcome collaboration on it if you're interested.

There's not nearly enough self-hosted AI support for the .NET platform, IMO.

**Comment by deatos** [comment]
I am working on removing the need for that dll,  I have found the licensing for it and have published the binary and it's license in a fix branch as a temporary measure until I figure something else out.

**Comment by StevenGann** [comment]
@deatos Pinging you here. My second PR is ready.
I have more work to do, but this is about as far as I can go without more communication from you.

**Comment by deatos** [comment]
Hello @StevenGann,  I will review and merge this today and get to your other questions,  being that TFIDF was never fully implemented I am considering pulling it out and replacing it later on down the road with another library or possibly coding it from scratch.  What are your thoughts on this?  I do not really like the idea of shipping the external 3rd party binaries even if they are permissibly licensed.

**Comment by StevenGann** [comment]
I agree with not wanting to bundle in third party binaries, if possible. There's a number of reasons, one being that I would like to use HyperVectorDB on Linux and Android and to support AoT compilation.

**Comment by deatos** [comment]
I have merged your pull and have removed the binaries and references to them.  Later today I will publish a nuget and look into automating the publishing of them.

**Comment by deatos** [comment]
Nuget has been published and is awaiting validation/indexing: https://www.nuget.org/packages/HyperVectorDB

**Comment by deatos** [comment]
Nuget is available and ReadMe has been updated.
